import { GoogleGenAI, Type } from '@google/genai';
import { AnalysisOption, ImageAnalysisResult } from '../types';

/**
 * Initializes the GoogleGenAI client.
 * API Key is expected from process.env.API_KEY.
 */
const getGeminiClient = () => {
  if (!process.env.API_KEY) {
    throw new Error('API_KEY environment variable is not set.');
  }
  return new GoogleGenAI({ apiKey: process.env.API_KEY });
};

/**
 * Analyzes an image based on selected options and generates a descriptive prompt.
 * @param base64Image The base64 encoded image data (e.g., 'data:image/png;base64,...').
 * @param options An array of AnalysisOption to guide the description.
 * @param otherAnalysisText Optional custom text for analysis if 'OTHER' option is selected.
 * @param isDetailedRequest If true, prompts the AI for more detailed descriptions.
 * @returns A promise that resolves to the generated descriptive prompt.
 */
export const analyzeImage = async (
  base64Image: string,
  options: AnalysisOption[],
  otherAnalysisText: string = '',
  isDetailedRequest: boolean = false, // New parameter
): Promise<ImageAnalysisResult> => { // Changed return type to ImageAnalysisResult
  try {
    const ai = getGeminiClient();

    const [mimeType, data] = base64Image.split(';base64,');
    if (!data) {
      throw new Error('Invalid base64 image format.');
    }

    let promptParts: string[] = [];
    let schemaProperties: { [key: string]: any } = {};

    const isNoOptionsSelected = options.length === 0;

    // Define standard options and their corresponding schema properties
    const standardOptions = [
      { enum: AnalysisOption.CHARACTER_ATTIRE, prompt: '人物的裝束（風格、顏色、面料、配件）', schemaKey: 'characterAttire', description: '詳細描述人物的裝束，包括風格、顏色、面料、配件等，嚴格不包含人物姿勢、表情、照片背景或鏡頭角度等其他類別的細節。' },
      { enum: AnalysisOption.CHARACTER_POSE, prompt: '人物的姿勢和動態，不包括面部表情。', schemaKey: 'characterPose', description: '詳細描述人物的姿勢和動態，不包含面部表情、裝束、照片背景或鏡頭角度等其他類別的細節。' },
      { enum: AnalysisOption.CHARACTER_EXPRESSION, prompt: '人物的面部表情和情緒', schemaKey: 'characterExpression', description: '詳細描述人物的面部表情和情緒，嚴格不包含姿勢、裝束、照片背景或鏡頭角度等其他類別的細節。' },
      { enum: AnalysisOption.PHOTO_BACKGROUND, prompt: '照片的背景（場景、元素、光線、氛圍）', schemaKey: 'photoBackground', description: '詳細描述照片的背景，包括場景、元素、光線、氛圍等，嚴格不包含人物裝束、姿勢、表情或鏡頭角度等其他類別的細節。' },
      { enum: AnalysisOption.CAMERA_ANGLE, prompt: '鏡頭角度（視角、距離、高度）', schemaKey: 'cameraAngle', description: '詳細描述鏡頭角度，包括視角、距離、高度等，嚴格不包含人物裝束、姿勢、表情或照片背景等其他類別的細節。' },
    ];

    if (isNoOptionsSelected) {
      // Default to all standard options if none are selected
      standardOptions.forEach(opt => {
        promptParts.push(opt.prompt);
        schemaProperties[opt.schemaKey] = { type: Type.STRING, description: opt.description };
      });
    } else {
      // Add selected standard options
      standardOptions.forEach(opt => {
        if (options.includes(opt.enum)) {
          promptParts.push(opt.prompt);
          schemaProperties[opt.schemaKey] = { type: Type.STRING, description: opt.description };
        }
      });
      // Add 'OTHER' option if selected and text is provided
      if (options.includes(AnalysisOption.OTHER) && otherAnalysisText.trim()) {
        promptParts.push(`用戶指定的內容："${otherAnalysisText.trim()}"`);
        schemaProperties.otherAnalysis = { type: Type.STRING, description: '詳細描述用戶指定的其他分析內容，嚴格僅限於此指定內容。' };
      }
    }

    if (Object.keys(schemaProperties).length === 0) {
      throw new Error('請選擇至少一個有效的分析選項或輸入「其他」的內容。');
    }

    // Modify system instruction and user prompt for detailed requests
    let systemInstruction = `你是一個圖像分析AI，專門為AI圖像編輯生成描述。你的任務是從提供的圖片中提取並描述用戶指定的方面。`;
    let userPrompt = `請分析圖片中關於以下指定內容，並以JSON格式輸出。每個描述都應直接、精簡，且嚴格僅限於其對應的類別。輸出必須嚴格遵循提供的JSON結構，不含任何額外文字。`;

    if (isDetailedRequest) {
      systemInstruction = `你是一個圖像分析AI，專門為AI圖像編輯生成詳細且具體的描述。你的任務是從提供的圖片中提取並描述用戶指定的方面。`;
      userPrompt = `請分析圖片中關於以下指定內容，並以JSON格式輸出。每個描述都應提供盡可能多的細節和上下文，具體且詳盡，且嚴格僅限於其對應的類別。輸出必須嚴格遵循提供的JSON結構，不含任何額外文字。`;
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: [
        { text: userPrompt },
        {
          inlineData: {
            mimeType: mimeType.replace('data:', ''),
            data: data,
          },
        },
      ],
      config: {
        systemInstruction: systemInstruction,
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: schemaProperties,
          propertyOrdering: Object.keys(schemaProperties), // Maintain order for consistency
        },
      },
    });

    const jsonStr = response.text?.trim();
    if (!jsonStr) {
      throw new Error('No JSON output generated by the model. It might be blocked due to safety concerns or other issues.');
    }

    // Attempt to parse JSON
    try {
      const parsedResult: ImageAnalysisResult = JSON.parse(jsonStr);
      return parsedResult;
    } catch (parseError) {
      console.error('Failed to parse JSON response:', jsonStr, parseError);
      throw new Error('模型返回的數據格式不正確。請檢查模型輸出是否符合預期的JSON結構。');
    }
  } catch (error: any) {
    console.error('Error analyzing image:', error);
    if (error.response && error.response.status) {
      // Handle specific HTTP errors from the API
      if (error.response.status === 400) {
        throw new Error('Bad Request: The request was malformed or invalid. Check your input data.');
      } else if (error.response.status === 401 || error.response.status === 403) {
        throw new Error('Authentication Error: Invalid or missing API key. Please ensure your API key is correctly configured.');
      } else if (error.response.status === 429) {
        throw new Error('Rate Limit Exceeded: Too many requests. Please try again after some time.');
      } else if (error.response.status >= 500) {
        throw new Error('Server Error: The AI service encountered an issue. Please try again later.');
      }
    }
    throw new Error(`Failed to analyze image: ${error.message || 'Unknown error'}`);
  }
};